name: template_env
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.3.5
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.10.1
  - numpy=2.2.3
  - pandas=2.2.2
  - pip=25.0.1
  - plotly=6.0.0
  - pmdarima=2.0.4
  - python=3.12
  - pip:
    - forecast-tools==0.4.0
